---
title: "Project Block 2: Advanced Statistics: Issues in multiple regression and Time-series Regression Models"
author: "Alberto Dorantes D."
date: "Sep 18, 2023"

abstract: This project is composed of 2 parts: 1) Advanced topics of multiple regression models, and 2) Basics of Time-series regression models

editor: visual
jupyter: python3
format:
  html: 
    toc: true
    toc-location: left
    theme: united
    highlight-style: breezedark
    number-sections: true
    fontsize: 1.1em
    linestretch: 1.7
---

# Part 1 - Advanced topics in multiple regression

In this part, you have to improve the multiple regression model you ended up in block 1 of the course (here is a description of the previous project).

The topics we will learn and apply in this part are the following:

Descriptive statistics for ratios

Treatment of extreme values for independent variables - winsorization

Estimation of correlation matrix using matrix algebra

Estimation of beta coefficients and standard errors in multiple regression using matrix algebra

The Hat Matrix

Identification of leverage observations

Identification of possible outliers

Identification and treatment of possible influential observations

How to treat and interpret categorical independent variables in a multiple regression model

You have to do the following:

Make sure that all the variable calculations and descriptive statistics is correct and complete (attend the feedback you received for this part). Do any correction or complete what you missed in the

For the Descriptive Statistics of your industry using only the most recent fiscal year observations (fiscalmonth=12, year=2022), do the following modifications:

For the ratios, instead of calculating the arithmetic mean of the ratios, calculate the weighted average of the ratios. To calculate the weighted average of a ratio, you have to divide the sum of the numerator variable by the sum of the denominator variable. For example, to calculate the weighted average of profit margin you first sum all the net income of all firms and then divide it by the sum of revenue of all firms.

Compare this weighted average with the arithmetic mean and the median. Which is the best measure for central tendency of the ratios? Interpret the weighted average of profit margin and asset turn over of your industry.

For the complete historical dataset of annual fiscal years (fiscalmonth=12 for all quarter-years), you have to calculate the following new independent variables:

Firm size as a categorical variable. For each quarter, you have to label firms in 3 equal groups: small, medium, big according to the market value of the firms.

Calculate the corresponding dummy (binary) variables for the firm size following the dummy encoding method.

Calculate operating earnings per share deflated by stock price: oepsp = (ebit / sharesoutstanding) / originalprice

Calculate earnings per share deflated by stock price: epsp = (netincome / sharesoutstanding) / originalprice

Calculate book-to-market ratio: bmr = bookvalue / marketvalue

In this model, the variable you have to use as dependent variable will be annual stock returns (instead of quarterly returns) one quarter in the future (f1.ry).

Winsorization of ratios

You have to check for very extreme values for the following ratios: profit margin, asset turn over, oepsp, bmr. Apply winsorization in case of very extreme values (keep at lest 98% of original values for each winsorization). Use the histogram to decide the level of winsorization.

Multicollienarity

Do the multicollienarity test considering all numeric independent variables:

profit margin, asset turn over, oepsp, bmr

Interpret the test. If there is a multicollienarity problem, propose how to solve it.

-   Run a first multiple regression model to examine whether the financial ratios and firm size explain/predict future annual stock returns (one quarter later). For the ratios, use the winsorized version (if the ratio has extreme values)

-   Interpret your model

    -   Interpret the results of each coefficient (beta and their statistical significance)

    -   Interpret the R-squared of the model

-   Run a multiple regression but now using only the last complete year of data (year=2022)

    -   What differences do you see compared with the previous model? Explain

-   Using this cross-sectional dataset with only annual data for 2022, you have to do the following:

    -   Using matrix algebra calculate the beta coefficients of the same regression model

    -   Using matrix algebra calculate the standard errors of the beta coefficients

    -   Using matrix algebra calculate the Hat Matrix

    -   With the hat matrix identify possible leverage observations

    -   Identify possible outliers using studentized residuals

    -   Identify possible outliers using Cook's distance

    -   Using studentized residuals and Cook's distance identify possible influential observations

    -   List the influential observations and decide whether to drop them or keep some of them

    -   Re-run the multiple regression model without the influential observation

        -   Compare the model with the previous one. Which model was better? Explain the differences

-   Deliverables

This case must be done by each student and the work must be original. Please avoid possible interpretations of plagiarism.

For each deliverable you have to submit a Jupyter Notebook (.ipynb and .html files). document

# Evaluation criteria

The evaluation criteria will be:

| Section                                    | Weight | Notes                                                                                                                                                                                    |
|---------------|---------------|-------------------------------------------|
| Data management and Descriptive statistics | 50%    | Document your work. You have to explain what you did and also you have to clearly responded to each of the business questions                                                            |
| Statistical modeling                       | 40%    | Document your work. Make sure you provide a very clear interpretation of your models. Remember that you must interpret each coefficient and their corresponding statistical significance |
| Conclusion                                 | 10%    | Provide a concise conclusion of your analysis according to the result of your models. Make sure you respond the main business questions                                                  |
|                                            |        |                                                                                                                                                                                          |
