---
title: "Project Block 1: Understanding profitability in the US financial market"
author: "Alberto Dorantes D."
date: "August 8, 2023"

abstract: This is business case prepared for the Statistics Module (Bloque 1) of the Advanced AI concentration

editor: visual
jupyter: python3
format:
  html: 
    toc: true
    toc-location: left
    theme: united
    highlight-style: breezedark
    number-sections: true
    fontsize: 1.1em
    linestretch: 1.7
---

# Case Description

You were hired as a data scientist in an important mutual fund firm in the department of financial analysis. The firm has been doing financial analysis and financial forecast for several years. You were hired to come up with alternative approaches to do descriptive analytics in order to find better future alternatives for forecasting methods.

You have to analyze historical quarterly financial statements of all US public firms listed in the New York Exchange and NASDAQ. You will receive this dataset in a .csv format.

You have to carefully read the data dictionary to understand each variable and the dataset to understand its structure.

# Business Questions

All your data and statistical analysis has to be tailored to respond the following questions:

## General questions:

By industry, what is the composition of US public firms in terms of firm size, sales performance and profitability?

Why some firms are more profitable than others? Which factors/variables from financial statements are related to stock returns?

## Specific questions:

### About descriptive statistics:

#### Considering the most recent financial quarter of the dataset:

-   Show how many firms by industry there are in the sample

-   For each industry (and for all industries), what can you say about the typical firm size in terms of market value and book value? How much these variables change within each industry? How firm size (in market value) is distributed?

-   For each industry (and for all industries), what can you say about profit margin of firms? show a) descriptive statistics of profit margin and b) plot(s) to illustrate how profit margin changes across industries.

-   Which are the biggest 10 US firms in terms of market value and how far they are from the typical size of a US firm?

-   Which are the biggest 10 US firms in terms of book value and how far they are from the typical size of a US firm?

#### Considering the whole history of financial data for all firms:

-   How can you measure firm profitability that can be used to compare performance among firms of different sizes? Select and justify at least 3 measures and show descriptive statistics

-   Calculate and explain earnings per share deflated by price.

### **About statistical modeling**

-   You have to select a group of firms according to their general industry classification:

    -   Manufacturing industries

    -   Commercial industries (retail and wholesale)

    -   Service industries

    -   Financial services

-   Using your subset of firms that belong to your industry, which factors (variables) might be related to annual stock return one quarter in the future? Select at least 3 factors and briefly explain why you think might be related to stock returns.

    -   Do histograms for each factor/variables and interpret them

    -   Do plots to visualize the possible relationship each factor might have with the dependent variable.

    -   Show descriptive statistics of these factors

-   Design and run a multiple regression model to examine whether your selected factors and earnings per share deflated by price can explain/predict annual stock returns. You have to control for industry and firm size. To control for these variables you have to include them as extra independent variables in the model

    -   Your independent variables must be in the right scale so that you can compare the values of the variables among different firms of any size

    -   For each independent variable you have to check for outliers and do the corresponding adjustments to avoid unreliable results in your regression model

    -   You must check for possible multicollinearity problems. Briefly explain what is multicollinearity, run and interpret the corresponding test

-   Interpret your model

    -   Interpret the results of each coefficient (beta and their statistical significance)

    -   Interpret the R-squared of the model

-   Adjustments to your model. If there is one or more independent variables (factors or control variables) that were not significant, drop them from your model. You have to run and interpret your final model.

# Deliverables

This case must be done by each student and the work must be original. Please avoid possible interpretations of plagiarism.

Deliverable 1: Up to Descriptive Statistics

Deliverable 2: Complete document including Statistical Modeling

For each deliverable you have to submit a Jupyter Notebook (.ipynb and .html files). document

# Evaluation criteria

The evaluation criteria will be:

| Section                                    | Weight | Notes                                                                                                                                                                                    |
|--------------------------------------------|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Data management and Descriptive statistics | 50%    | Document your work. You have to explain what you did and also you have to clearly responded to each of the business questions                                                            |
| Statistical modeling                       | 40%    | Document your work. Make sure you provide a very clear interpretation of your models. Remember that you must interpret each coefficient and their corresponding statistical significance |
| Conclusion                                 | 10%    | Provide a concise conclusion of your analysis according to the result of your models. Make sure you respond the main business questions                                                  |
|                                            |        |                                                                                                                                                                                          |
